In [2]:
from sklearn.datasets import load_digits
from sklearn.utils import shuffle

import pandas as pd

In [4]:
digits = load_digits()

In [5]:
df = pd.DataFrame(digits.data)
df['y'] = digits.target

In [30]:
df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,y
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4
5,0.0,0.0,12.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,9.0,16.0,16.0,10.0,0.0,0.0,5
6,0.0,0.0,0.0,12.0,13.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,9.0,15.0,11.0,3.0,0.0,6
7,0.0,0.0,7.0,8.0,13.0,16.0,15.0,1.0,0.0,0.0,...,0.0,0.0,0.0,13.0,5.0,0.0,0.0,0.0,0.0,7
8,0.0,0.0,9.0,14.0,8.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,11.0,16.0,15.0,11.0,1.0,0.0,8
9,0.0,0.0,11.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,9.0,12.0,13.0,3.0,0.0,0.0,9

In [8]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,y
count,1797.0,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000,...,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000,1797.000000
mean,0.0,0.303840,5.204786,11.835838,11.848080,5.781859,1.362270,0.129661,0.005565,1.993879,...,0.206455,0.000556,0.279354,5.557596,12.089037,11.809126,6.764051,2.067891,0.364496,4.490818
std,0.0,0.907192,4.754826,4.248842,4.287388,5.666418,3.325775,1.037383,0.094222,3.196160,...,0.984401,0.023590,0.934302,5.103019,4.374694,4.933947,5.900623,4.090548,1.860122,2.865304
min,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.0,0.000000,1.000000,10.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,11.000000,10.000000,0.000000,0.000000,0.000000,2.000000
50%,0.0,0.000000,4.000000,13.000000,13.000000,4.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.000000,13.000000,14.000000,6.000000,0.000000,0.000000,4.000000
75%,0.0,0.000000,9.000000,15.000000,15.000000,11.000000,0.000000,0.000000,0.000000,3.000000,...,0.000000,0.000000,0.000000,10.000000,16.000000,16.000000,12.000000,2.000000,0.000000,7.000000
max,0.0,8.000000,16.000000,16.000000,16.000000,16.000000,16.000000,15.000000,2.000000,16.000000,...,13.000000,1.000000,9.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,9.000000

In [9]:
x_names = df.keys()[:-1]

"\nmnist = fetch_mldata('MNIST original')\nx = mnist.data\ny = mnist.target\ndf = pd.DataFrame(x)\ndf['y'] = y\n\nfor v in df.keys():\n    m = df[v].mean()\n    if m == 0:\n        df.drop(v, axis=1, inplace=True)\n        print 'Drop'\n        \ndf.to_csv('MNIST.csv', index=False)\n"

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchC

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [12]:
x_names = df.keys()[:-1]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df[x_names], 
                                                    df['y'], 
                                                    test_size=0.2)

In [14]:
l_model = LogisticRegression(fit_intercept=True)
l_model.fit(X_train,  y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
confusion_matrix(y_train, l_model.predict(X_train))

array([[142,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 136,   0,   0,   0,   0,   0,   0,   2,   0],
       [  0,   0, 143,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 139,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 144,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 153,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 153,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 138,   0,   0],
       [  0,   4,   0,   1,   0,   0,   0,   0, 141,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   3, 138]])

In [16]:
confusion_matrix(y_test, l_model.predict(X_test))

array([[36,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 40,  0,  0,  0,  0,  0,  0,  4,  0],
       [ 0,  0, 32,  2,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 43,  0,  0,  0,  0,  0,  1],
       [ 0,  1,  0,  0, 36,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 29,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 28,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 41,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0,  0, 27,  0],
       [ 0,  0,  0,  1,  0,  1,  0,  0,  1, 36]])

In [17]:
knn_grid = {'n_neighbors': [3, 5, 10, 15]}
grid = GridSearchCV(KNeighborsClassifier(), knn_grid, cv=5)

In [18]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_neighbors': [3, 5, 10, 15]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score=True, scoring=None, verbose=0)

In [19]:
grid.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [21]:
knn_model = grid.best_estimator_

In [24]:
knn_model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [27]:
confusion_matrix(y_train, knn_model.predict(X_train))

array([[142,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 138,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 143,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 137,   0,   0,   0,   2,   0,   0],
       [  0,   0,   0,   0, 144,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 151,   1,   0,   0,   1],
       [  0,   0,   0,   0,   0,   0, 153,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 138,   0,   0],
       [  0,   3,   0,   0,   0,   0,   0,   0, 143,   0],
       [  0,   0,   0,   3,   1,   0,   0,   0,   0, 137]])

In [29]:
confusion_matrix(y_test, knn_model.predict(X_test))

array([[36,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 44,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 34,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 37,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 29,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 28,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 41,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 28,  0],
       [ 0,  0,  0,  0,  0,  2,  0,  0,  2, 35]])

In [34]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, knn_model.predict(X_test))

0.98888888888888893

In [33]:
accuracy_score(y_train, knn_model.predict(X_train))

0.99234516353514268

In [37]:
predicted_values = knn_model.predict(df[x_names])

In [41]:
df['predicted_values'] = predicted_values

In [45]:
df[df['y'] != df['predicted_values']]

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,y,predicted_values
5,0.0,0.0,12.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,9.0,16.0,16.0,10.0,0.0,0.0,5,9
69,0.0,0.0,6.0,12.0,13.0,6.0,0.0,0.0,0.0,6.0,...,0.0,0.0,6.0,11.0,0.0,0.0,0.0,0.0,9,4
129,0.0,0.0,7.0,13.0,15.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,13.0,10.0,0.0,0.0,0.0,8,1
547,0.0,0.0,2.0,10.0,16.0,11.0,1.0,0.0,0.0,0.0,...,0.0,0.0,5.0,11.0,16.0,3.0,0.0,0.0,9,8
794,0.0,0.0,0.0,2.0,15.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,14.0,11.0,0.0,0.0,8,1
813,0.0,0.0,3.0,4.0,10.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,3.0,11.0,16.0,16.0,3.0,9,3
1038,0.0,1.0,11.0,16.0,11.0,1.0,0.0,0.0,0.0,6.0,...,0.0,0.0,14.0,8.0,4.0,0.0,0.0,0.0,9,3
1100,0.0,1.0,12.0,15.0,10.0,2.0,0.0,0.0,0.0,4.0,...,0.0,0.0,11.0,12.0,13.0,4.0,0.0,0.0,9,8
1118,0.0,0.0,3.0,11.0,14.0,12.0,3.0,0.0,0.0,2.0,...,0.0,3.0,7.0,14.0,5.0,0.0,0.0,0.0,3,7
1361,0.0,0.0,4.0,9.0,13.0,13.0,0.0,0.0,0.0,1.0,...,0.0,0.0,3.0,12.0,14.0,8.0,0.0,0.0,5,6
1553,0.0,0.0,1.0,8.0,13.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,12.0,5.0,0.0,0.0,8,1
1582,0.0,0.0,6.0,14.0,16.0,15.0,1.0,0.0,0.0,9.0,...,0.0,0.0,9.0,16.0,1.0,0.0,0.0,0.0,9,5
1605,0.0,0.0,9.0,16.0,16.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,11.0,16.0,12.0,0.0,0.0,0.0,3,7
1658,0.0,0.0,7.0,16.0,16.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7.0,16.0,16.0,11.0,0.0,0.0,9,3
1662,0.0,0.0,7.0,15.0,16.0,12.0,0.0,0.0,0.0,12.0,...,0.0,0.0,10.0,12.0,1.0,0.0,0.0,0.0,9,5